# ================================
# MAIN APP (unipilot.in)
# ================================
server {
    listen 80;
    server_name unipilot.in www.unipilot.in;

    location /api/ {
        proxy_pass http://unipilot-backend:3000/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location / {
        proxy_pass http://unipilot-main-frontend:80;
        proxy_set_header Host $host;
    }
}


# ================================
# EXAM MANAGEMENT (exam.unipilot.in)
# ================================
server {
    listen 80;
    server_name examsection.unipilot.in;

    location /api/ {
        proxy_pass http://unipilot-backend:3000/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location / {
        proxy_pass http://unipilot-exam-frontend:80;
        proxy_set_header Host $host;
    }
}

