export const DEGREE_LABELS = {
  btech: "B.Tech",
  mtech: "M.Tech",
  bba: "BBA",
  mba: "MBA",
  bsc: "B.Sc",
  msc: "M.Sc",
  bca: "BCA",
  mca: "MCA",
  bcom: "B.Com",
  mcom: "M.Com",
  ba: "BA",
  ma: "MA",
  phd: "Ph.D",
  diploma: "Diploma",
};